FROM alpine:latest

RUN echo -e "https://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories && \
    echo -e "https://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories

RUN adduser -D heroku
USER heroku
RUN mkdir --parents $HOME/.config/qBittorrent/ $HOME/.config/rclone/ && \
    echo -e "[LegalNotice]\nAccepted=true" > $HOME/.config/qBittorrent/qBittorrent.conf

USER root
RUN apk update --no-cache && \
    apk add --no-cache qbittorrent-nox rclone fuse