FROM archlinux:base-devel

#RUN echo 'Server = https://mirror.osbeck.com/archlinux/$repo/os/$arch' > /etc/pacman.d/mirrorlist
RUN sed -i 's/NoProgressBar/#NoProgressBar/;s/ParallelDownloads = 5/ParallelDownloads = 20/;s/#Color/Color/' /etc/pacman.conf && \
    pacman-key --init && \
    pacman-key --recv-key FBA220DFC880C036 --keyserver keyserver.ubuntu.com && \
    pacman-key --lsign-key FBA220DFC880C036 && \
    pacman -U --noconfirm 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst' && \
    echo -e "\n[chaotic-aur]\nInclude = /etc/pacman.d/chaotic-mirrorlist" >> /etc/pacman.conf
   
RUN useradd -m -G wheel x0rzavi && \
    echo "root:1229" | chpasswd && \
    echo "x0rzavi:1229" | chpasswd && \
    ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime && \
    echo "%wheel ALL=(ALL:ALL) ALL" > /etc/sudoers.d/00-wheel && \
    echo "Defaults pwfeedback" > /etc/sudoers.d/01-feedback

RUN pacman -Syyu --noconfirm
RUN pacman -S --noconfirm git wget curl btop paru micro nano vim openssh fish && \
    sed -i 's/#BottomUp/BottomUp/;s/#SudoLoop/SudoLoop/' /etc/paru.conf
RUN yes | paru -Sccd

USER x0rzavi
WORKDIR /home/x0rzavi
RUN echo "1229" | chsh -s /bin/fish