name: Qbittorent on heroku
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 */6 * * *'
  push:
      paths:
        - 'Dockerfile.heroku-qb'
        - '.github/workflows/heroku-qb.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Login
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Buildx setup
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          install: true

      - name: Build image
        uses: docker/build-push-action@master
        with:
          context: .
          file: Dockerfile.heroku-qb
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: x0rzavi/heroku-qb:latest
          cache-from: type=registry,ref=x0rzavi/heroku-qb:buildcache
          cache-to: type=registry,ref=x0rzavi/heroku-qb:buildcache,mode=max
